In [7]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import metrics

### 실습 과제 1. 데이터 불러온 후 NaN 값이 있다면 해당 행 제거하고, train_data : test_data = 7:3 split
#### 종속변수는 PKT_Y, 나머지 변수들이 독립변수

In [8]:
df = pd.read_csv("contest.csv")
df.head()

No.   LOT_ID  WF_ID  X_AXIS  Y_AXIS GRADE_CD  G_A  G_B  G_C  G_D  ...  \
0  48159  ABC1236     13      59      32       SQ    0    0    0    0  ...   
1  60178  ABC1258      2      45      14       SQ    0    0    0    0  ...   
2  60860  ABC1258     15      50      14       SQ    0    0    0    0  ...   
3  25012  ABC1236      1      45      13       SQ    0    0    0    0  ...   
4  86262  ABC1236      3      51      13       SQ    0    0    0    0  ...   

   Weight_Bound_L  Weight_Bound_M  Weight_Bound_N  Weight_Bound_O  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   Weight_Bound_P  Weight_Bound_Q  Weight_Bound_R  Weight_Bound_S  \
0             0.0             0.0        0.000000        0.000000   
1             0.0             0.0        0.000000        0.000000   
2             0.0             0.0        3.452381       81.583333   
3             0.0             0.0        0.000000        0.000000   
4             0.0             0.0        0.000000        0.000000   

   Weight_Bound_T  PKT_Y  
0             0.0    1.0  
1             0.0    1.0  
2             0.0    1.0  
3             0.0    1.0  
4             0.0    1.0  

[5 rows x 87 columns]

In [9]:
print(df.isnull().sum())

No.                 0
LOT_ID              0
WF_ID               0
X_AXIS              0
Y_AXIS              0
                 ... 
Weight_Bound_Q      0
Weight_Bound_R      0
Weight_Bound_S      0
Weight_Bound_T      0
PKT_Y             530
Length: 87, dtype: int64


In [10]:
df = df.dropna()
print(df.isnull().sum())

No.               0
LOT_ID            0
WF_ID             0
X_AXIS            0
Y_AXIS            0
                 ..
Weight_Bound_Q    0
Weight_Bound_R    0
Weight_Bound_S    0
Weight_Bound_T    0
PKT_Y             0
Length: 87, dtype: int64


In [11]:
ndf = df.iloc[:,6:]
ndf.head()

G_A  G_B  G_C  G_D  G_E  G_F  G_G  G_H  G_I  G_J  ...  Weight_Bound_L  \
0    0    0    0    0    0    0    0  0.0    0    0  ...             0.0   
1    0    0    0    0    0    0    0  0.0    2    0  ...             0.0   
2    0    0    0    0    0    0    0  0.0    0    0  ...             0.0   
3    0    0    0    0    4    0    0  0.0    0    0  ...             0.0   
4    0    0    0    0    0    0    0  0.0    0    0  ...             0.0   

   Weight_Bound_M  Weight_Bound_N  Weight_Bound_O  Weight_Bound_P  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   Weight_Bound_Q  Weight_Bound_R  Weight_Bound_S  Weight_Bound_T  PKT_Y  
0             0.0        0.000000        0.000000             0.0    1.0  
1             0.0        0.000000        0.000000             0.0    1.0  
2             0.0        3.452381       81.583333             0.0    1.0  
3             0.0        0.000000        0.000000             0.0    1.0  
4             0.0        0.000000        0.000000             0.0    1.0  

[5 rows x 81 columns]

In [12]:
Input = ndf.drop('PKT_Y', axis = 1)
Output = ndf.loc[:, 'PKT_Y']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Input, Output, test_size = 0.3, random_state = 10)

train data (1379, 80)
(591, 80)


### 실습 과제 2. 선형 커널, 3차항 커널, RBF 커널, 시그모이드 커널로 각각 SVM 모델 구현 후 accuracy, F1 score, confusion matrix, precision, recall (C=1, gamma = 0.1)

### RBF

In [74]:
from sklearn import svm
from sklearn import metrics

svm_rbf = svm.SVC(kernel='rbf', C=1, gamma = 0.1)

svm_rbf.fit(X_train, y_train)

y_pred = svm_rbf.predict(X_test)

con_mat = metrics.confusion_matrix(y_test, y_pred)
acc_lin2 = metrics.accuracy_score(y_test, y_pred)
f1_lin2 = metrics.f1_score(y_test, y_pred)

precision = con_mat[1][1]/(con_mat[1][1]+con_mat[0][1])
recall = con_mat[1][1]/(con_mat[1][1]+con_mat[1][0])

print('accuracy:', acc_lin2)
print('f1 score:', f1_lin2)
print('='*30)
print('confusion mat : ')
print(con_mat)
print('precision:',precision)
print('recall:', recall)

accuracy: 0.5769881556683587
f1 score: 0.6458923512747875
confusion mat : 
[[113 173]
 [ 77 228]]
precision: 0.5685785536159601
recall: 0.7475409836065574


### 3차항

In [75]:
svm_poly = svm.SVC(kernel = 'poly', degree = 3, C = 1, gamma = 0.1)

svm_poly.fit(X_train, y_train)

y_pred = svm_poly.predict(X_test)

con_mat = metrics.confusion_matrix(y_test, y_pred)
acc_lin2 = metrics.accuracy_score(y_test, y_pred)
f1_lin2 = metrics.f1_score(y_test, y_pred)

precision = con_mat[1][1]/(con_mat[1][1]+con_mat[0][1])
recall = con_mat[1][1]/(con_mat[1][1]+con_mat[1][0])

print('accuracy:', acc_lin2)
print('f1 score:', f1_lin2)
print('='*30)
print('confusion mat : ')
print(con_mat)
print('precision:',precision)
print('recall:', recall)

accuracy: 0.5820642978003384
f1 score: 0.5240847784200385
confusion mat : 
[[208  78]
 [169 136]]
precision: 0.6355140186915887
recall: 0.4459016393442623


### 시그모이드

In [78]:
svm_sig = svm.SVC(kernel = 'sigmoid', C = 1, gamma = 0.1)

svm_sig.fit(X_train, y_train)

y_pred = svm_sig.predict(X_test)

con_mat = metrics.confusion_matrix(y_test, y_pred)
acc_lin2 = metrics.accuracy_score(y_test, y_pred)
f1_lin2 = metrics.f1_score(y_test, y_pred)

precision = con_mat[1][1]/(con_mat[1][1]+con_mat[0][1])
recall = con_mat[1][1]/(con_mat[1][1]+con_mat[1][0])

print('accuracy:', acc_lin2)
print('f1 score:', f1_lin2)
print('='*30)
print('confusion mat : ')
print(con_mat)
print('precision:',precision)
print('recall:', recall)

accuracy: 0.36717428087986465
f1 score: 0.3848684210526316
confusion mat : 
[[100 186]
 [188 117]]
precision: 0.38613861386138615
recall: 0.3836065573770492


### 선형

In [77]:
svm_lin = svm.SVC(kernel = 'poly', degree = 1, C = 1, gamma = 0.1)

svm_lin.fit(X_train, y_train)

y_pred = svm_lin.predict(X_test)

con_mat = metrics.confusion_matrix(y_test, y_pred)
acc_lin2 = metrics.accuracy_score(y_test, y_pred)
f1_lin2 = metrics.f1_score(y_test, y_pred)

precision = con_mat[1][1]/(con_mat[1][1]+con_mat[0][1])
recall = con_mat[1][1]/(con_mat[1][1]+con_mat[1][0])

print('accuracy:', acc_lin2)
print('f1 score:', f1_lin2)
print('='*30)
print('confusion mat : ')
print(con_mat)
print('precision:',precision)
print('recall:', recall)

accuracy: 0.5803722504230119
f1 score: 0.4979757085020242
confusion mat : 
[[220  66]
 [182 123]]
precision: 0.6507936507936508
recall: 0.40327868852459015


### 실습 과제 3. 하이퍼 파라미터 C 값(0.01, 0.1, 1, 10)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [83]:
C_list = [0.01, 0.1, 1, 10]

for Cv in C_list:
    svm_rbf = svm.SVC(kernel='rbf', C = Cv, gamma = 0.1)

    svm_rbf.fit(X_train, y_train)

    y_pred = svm_rbf.predict(X_test)

    acc_lin2 = metrics.accuracy_score(y_test, y_pred)
    f1_lin2 = metrics.f1_score(y_test, y_pred)

    print('C:', Cv)
    print('accuracy:', acc_lin2)
    print('f1 score:', f1_lin2)
    print('='*30)

C: 0.01
accuracy: 0.5160744500846024
f1 score: 0.6808035714285715
C: 0.1
accuracy: 0.5465313028764806
f1 score: 0.6555269922879178
C: 1
accuracy: 0.5769881556683587
f1 score: 0.6458923512747875
C: 10
accuracy: 0.5702199661590525
f1 score: 0.6520547945205479


- C 값이 증가할수록 accuracy가 증가하는 듯하나 C가 1일 때 보다 10일 때 accuracy가 조금 더 낮다는 것을 알 수 있음
- C 값이 증가할수록 오류를 허용하지 않으며, 감소할수록 오류를 허용함을 확인할 수 있음

### 실습 과제 4. 하이퍼 파라미터 gamma 값(0.005,0.01,0.1, 1)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [85]:
gamma_list = [0.005,0.01,0.1,1]

for g in gamma_list:
    svm_rbf = svm.SVC(kernel='rbf', C = 1, gamma = g)

    svm_rbf.fit(X_train, y_train)

    y_pred = svm_rbf.predict(X_test)

    acc_lin2 = metrics.accuracy_score(y_test, y_pred)
    f1_lin2 = metrics.f1_score(y_test, y_pred)

    print('gamma:', g)
    print('accuracy:', acc_lin2)
    print('f1 score:', f1_lin2)
    print('='*30)

gamma: 0.005
accuracy: 0.6040609137055838
f1 score: 0.5894736842105263
gamma: 0.01
accuracy: 0.6006768189509306
f1 score: 0.6143790849673203
gamma: 0.1
accuracy: 0.5769881556683587
f1 score: 0.6458923512747875
gamma: 1
accuracy: 0.544839255499154
f1 score: 0.6699386503067485


- gamma값이 증가할수록 정확도는 감소하되 f1 score가 증가하는 것을 알 수 있음
- gamma값이 증가할수록 학습 데이터에 의존하여 결정 경계를 만들고 감소할수록 학습 데이터에 의존하지 않고 결정 경계를 직선에 가깝게 만듦을 확인할 수 있음

### 실습 과제 5. 하이퍼 파라미터 degree(1,2,3,4,5)에 따른 다항식 커널 SVM 모델 accuracy와 F1 score 변화 관찰

In [84]:
degree_list = [1,2,3,4,5]
for d in degree_list:
    svm_poly = svm.SVC(kernel = 'poly', degree = d, C = 1, gamma = 0.1)

    svm_poly.fit(X_train, y_train)

    y_pred = svm_poly.predict(X_test)

    acc_lin2 = metrics.accuracy_score(y_test, y_pred)
    f1_lin2 = metrics.f1_score(y_test, y_pred)
    
    print('degree:', d)
    print('accuracy:', acc_lin2)
    print('f1 score:', f1_lin2)
    print('='*30)

degree: 1
accuracy: 0.5803722504230119
f1 score: 0.4979757085020242
degree: 2
accuracy: 0.5668358714043993
f1 score: 0.5133079847908745
degree: 3
accuracy: 0.5820642978003384
f1 score: 0.5240847784200385
degree: 4
accuracy: 0.5820642978003384
f1 score: 0.5330812854442345
degree: 5
accuracy: 0.583756345177665
f1 score: 0.5477941176470589


- 차수가 높을수록 정확도의 차이는 크게 없지만 f1 score가 증가하는 것을 알 수 있음
- 차수가 높을수록 성능은 높아지나 시간이 오래 걸린다는 것을 확인할 수 있음